### ISSUE TITLE
Android版 の更新履歴一覧が欲しい。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon_Android#1]
https://github.com/ryotayama/Hayaemon/issues/222 からの移植(コピペ)です。

更新頻度が高いので早めに作らないと作業が徐々に大変になっていくと思います。

上部が新しい物になるように記述する。
_しかしこの作業やるとなると、作業漏れが起こりそうで怖いなぁ_

# 作例 

## Ver. 1.54 2018/6/8
- ハヤえもんAndroid版をオープンソース化に向けてソースコードを整理(リファクタリング)をした

## Ver.1.53  2018/5/31

- 期間限定の桜のアイコンを終了し、通常アイコンに変更した

**Comment by sugartarou** [comment]
> もう作業量がスゴいことになっているから作るのは無理そうだからCloseでも良いかも・・・。

とのことでiOS版はクローズしてたので、こっちもクローズ。
