### ISSUE TITLE
「ディスクの空き容量」という文言に違和感がある

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon_Android#107]
https://twitter.com/ryota_yama/status/1033581410454462465?s=21

![Image](https://i.imgur.com/iwj2TcE.jpg)

録音時、ディスクの空き容量が少なくなっている場合は、エラーを出すようにした！

https://twitter.com/yamaokakazuma/status/1033581770237599744?s=21

ディスク？ストレージでは？

厳密にはそうですね。
一般ユーザーの方には「ストレージ」と言っても伝わらないかもと思い、「ディスク」ならハードディスクという言葉が馴染みがあるので伝わるかなーと、いったん「ディスク」と表現してみました！

ノートパソコンもSSD搭載機種が増えてきて、保存領域をディスクと呼ぶのは丁度「巻き戻し」と同じようなミスマッチ感を伴うようになるかもしれませんねw

たしかにw
デジタル用語の一般ユーザーへの普及度合いとの兼ね合いがあって悩ましいところです。。

「本体」「端末内」とかっていうのはどうでしょうか？？(*･ω･)ﾉ

いいかもねー、現状iOS版も「ディスク」になってるからまとめて別途対応しよーかな！

〜〜引用ここまで〜〜

「ディスクの空き容量が少なくなっています」

↓

「本体の空き容量が少なくなっています」

もしくは

「端末内の空き容量が少なくなっています」

とするのはどうでしょうか。

ご意見頂戴したいです(*･ω･)ﾉ

**Comment by ryotayama** [comment]
直した！
![dmtqxekxoaeskju](https://user-images.githubusercontent.com/6075785/45069702-cd7a5000-b108-11e8-9414-65ef3fff5848.jpg)
