### ISSUE TITLE
ポップアップメニューについて、異なるUIのものが表示される

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#109]
- Android版ver.1.61

ポップアップメニューについて、異なるUIのものが表示されるのを修正したい。

- 再生リスト上の曲を長押しした場合
　→画面中央に表示されるメニュー
![dlk3ojiuyaevdeo](https://user-images.githubusercontent.com/6075785/44639049-c6f72480-a9f4-11e8-8e42-7124fa448d41.jpg)

- 「別の再生リストに移動」や「コピー」を押した場合
　→画面下部から上がってくるメニュー
![dlk3pb-uuaebzuw](https://user-images.githubusercontent.com/6075785/44639059-cc546f00-a9f4-11e8-9d5d-940c4f12419c.jpg)

**Comment by guxtuti-raven** [comment]
修正後
- 再生リスト上の曲を長押しした場合
　→画面中央に表示されるメニュー
![screenshot_20181030-233807](https://user-images.githubusercontent.com/33012932/47726221-60fd7680-dc9d-11e8-8ee6-b52dc3077a06.jpg)


- 「別の再生リストに移動」や「コピー」を押した場合
　→画面下部から上がってくるメニュー
![screenshot_20181030-233811](https://user-images.githubusercontent.com/33012932/47726257-75da0a00-dc9d-11e8-9a59-37714ba98d9f.jpg)
