### ISSUE TITLE
エフェクトのオプション設定のアイコンがiマークなのが違和感がある

### ISSUE THREAD

**Issue by KanzakiSaki** [ryotayama/Hayaemon_Android#121]
![Image](https://i.imgur.com/X9PXpSA.jpg)

ツイッターの鍵垢さんからの指摘です。

iはinformationの略で、設定ならsettingsなので違和感があるとの事。

りょーたさんいわく、最初はiOSのデフォルトのパーツを使っていたけど、今はiOSもAndroidもオリジナルで作っているとの事でした。

私はひょっとして＞マークだけでもいいのかも？と思ったけど、オンオフ切り替えそのものはチェックボックス形式にして、エフェクト名＋＞マークをタップでオプション設定画面でもいいかなーと。

エフェクト画面は並べ替えの要望（issue https://github.com/ryotayama/Hayaemon_iOS/issues/134 ）もあるので、併せて検討する必要がありそうです(*･ω･)ﾉ

関連issue（iOS版） https://github.com/ryotayama/Hayaemon_iOS/issues/154

**Comment by sugartarou** [comment]
現状iOSは > アイコン
リソース差し替えなので簡単にできるが。。対応するメリットもそんなにない。。

**Comment by sugartarou** [comment]
#332 があったのでこちらはクローズ。
