### ISSUE TITLE
通知センターから再生操作ができるようにしてほしい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon_Android#123]
https://twitter.com/ryota_yama/status/1039529241719713792?s=21
#ハヤえもんGooglePlayストアでのやりとり
虹スマッシュ（2018/09/10、14:15）
★★★★☆
イコライザーとか細かく設定できるのがすごくいい。 しかし、「flac」の拡張子のファイルが読み込めないのと、通知が表示されないのが残念……。

こちらから 2018/09/11 23:59 に返信
虹スマッシュさん、はじめまして！
ハヤえもん開発者のりょーたと申します₍₍ (ง*ᐛ)ว ⁾⁾
アプリをお褒めくださり、ありがとうございます！
嬉しいです！
flac対応したいです！　いずれ対応するので、もうしばらくお待ちくださいね。
「通知が表示されない」というのは具体的に言うと、どんな事でしょうか？
ご不便な点があるのであればぜひぜひ修正したいので、詳細を教えていただけると嬉しいです！
ツイッター（@ryota_yama）からご連絡いただく事もできます！

〜〜

https://twitter.com/recarendraven/statuses/1039529282148560896
たぶん！

こういうことじゃないかなぁ

自分の声が聴こえてきたww
「通知バーから操作できない」って話をしてるってことかな？？

たぶんそうなんじゃないかなぁ( ˘ω˘ )
そんな気がするぞぉ

〜〜

GooglePlayストア 虹スマッシュさんからの返信↓
返信ありがとうございます！
「通知が表示……」とは、音楽を再生したときに、通知センター(通知領域)に現在再生中の音楽を表示して欲しかったということです(音楽名、アルバム名、アプリの名前、一時停止、停止、戻る、次を再生などです)。
追記 書き忘れていたのですが、プレイリストからではなく、アルバム一覧みたいなものから再生できるようにもして欲しいです(ファイルの取り込みが大変なので……)。

〜〜引用ここまで〜〜

通知センターに表示させる機能としては

* アプリ名（ハヤえもん）
* 再生中の曲名
* アーティスト名
* 再生／一時停止ボタン
* 前へ／次へボタン

こんなところでしょうか。
（アルバム名はそもそも未対応なので）

iOS版ではできるので、確かに！と思いました‪(。-∀-)ゞ‬

**Comment by ryotayama** [comment]
いったん通知バーからコントロールできるように対応しましたが、たっくんの言ってるやつとか、アートワークの表示、長押しにより巻戻し／早送りなどは別途イシューを立てながら順次対応します！
