### ISSUE TITLE
歌詞を表示させながら録音したい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon_Android#131]
iOS版 https://github.com/ryotayama/Hayaemon_iOS/issues/179 のコピーです

https://twitter.com/ryota_yama/statuses/952452782161764352
現状のハヤえもんに対する不満。歌詞を見ながら録音できない。録音したあとにミックスできない。Aメロ、Bメロとかで分けて録音したやつをミックスできない。録音した音をツイッターとかで共有できない。

〜〜

歌詞を見ながら録音できると、nanaやカラオケアプリみたいでいいですよね。(*･ω･)ﾉ

**Comment by ryotayama** [comment]
#43 の対応時にAndroid版は歌詞を表示させながら録音できるようにしました！
iOS版もいずれ対応します！
