### ISSUE TITLE
歌詞表示画面で端末の戻るボタンを押したら、曲一覧画面に戻るようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#134]
- Android版ver.1.69

https://twitter.com/recarendraven/status/1046615560195268609
各画面の変移ってこんな感じじゃないですか。
![doztsrcvsaah6st](https://user-images.githubusercontent.com/6075785/46269782-3fb24900-c57e-11e8-91b9-d4b0ec92e14e.jpg)
で、Androidにはナビゲーションバーの｢戻る｣がある。
だから、例えば歌詞を見てる時に…説明難しい2枚目見て
![dozttupvaaih3jp](https://user-images.githubusercontent.com/6075785/46269785-450f9380-c57e-11e8-9ff7-028230659159.jpg)

https://twitter.com/ryota_yama/status/1046616472754085888
おぉ、これはまさにその通りかも！
ちょっと実現方法が分かんないけど、課題として登録しとく！

**Comment by arigayas** [comment]
これはどこに戻るのか書いて置いた方が良いと思います。

**Comment by ryotayama** [comment]
ありさん、ありがとー！
タイトル直しといた！
