### ISSUE TITLE
下から出てくるメニューについて、フォントサイズが統一されていない

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#136]
- Android版ver.1.69

https://twitter.com/recarendraven/status/1046625276732485633
同じ下からでるメニュー。
フォントサイズの差が…
![dozciweu4aaafhl](https://user-images.githubusercontent.com/6075785/46271366-337eb980-c587-11e8-94bf-6c88c236dabe.jpg)
![dozci1bu0aa2u3a](https://user-images.githubusercontent.com/6075785/46271367-35e11380-c587-11e8-98f0-28aedbf8d9ea.jpg)

**Comment by guxtuti-raven** [comment]
![screenshot_20181028-224300](https://user-images.githubusercontent.com/33012932/47616990-97ed5400-db06-11e8-9758-07878e4a8d63.jpg)
![screenshot_20181028-211959](https://user-images.githubusercontent.com/33012932/47616993-a3407f80-db06-11e8-8871-e0ad1f341c8f.jpg)
修正したもの
