### ISSUE TITLE
下から出てくるメニューについて、保存／エクスポート時に曲名が表示されるようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#137]
- Android版ver.1.69

https://twitter.com/recarendraven/status/1046625276732485633
エクスポートするときも曲名が出ると親切かなって思った！
![dozciweu4aaafhl](https://user-images.githubusercontent.com/6075785/46271415-7a6caf00-c587-11e8-9973-1d03189a106a.jpg)
![dozci1bu0aa2u3a](https://user-images.githubusercontent.com/6075785/46271420-7c367280-c587-11e8-8725-3c11fbf3ec34.jpg)

**Comment by guxtuti-raven** [comment]
修正前
![screenshot_20181028-224300](https://user-images.githubusercontent.com/33012932/47626903-cc95f580-db70-11e8-9032-8ed189da8532.jpg)

修正後
![screenshot_20181029-061443](https://user-images.githubusercontent.com/33012932/47626912-d4ee3080-db70-11e8-840e-500d6a849dd3.jpg)
