### ISSUE TITLE
イヤホンを抜いたら再生が止まるようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#138]
- 引っ越し元
https://github.com/ryotayama/Hayaemon/issues/126

ゆっきーさんのツイート: "イヤホン抜いても差しても再生止まらん( ˘ω˘ )"
https://twitter.com/guxtuti_yukine/status/992973479270993920

確認した環境：
ハヤえもんのバージョンは1.47。
Androidのバージョンは8.0.0

**Comment by mikuta0407** [comment]
Bluetoothイヤホンの接続断も同じくお願いします

**Comment by ryotayama** [comment]
メモ。
- Androidのイヤホンの抜き差しを検知する
https://qiita.com/masaibar/items/649c85a86e3ad4ef7c97
