### ISSUE TITLE
Bluetoothイヤホンのリモコン機能で操作ができない

### ISSUE THREAD

**Issue by mikuta0407** [ryotayama/Hayaemon_Android#139]
おそらく有線イヤホンのリモコンも同じかと思われますが､再生/一時停止等をしてもハヤえもんの操作ができず､別アプリが起動してそれを操作してしまいます

**Comment by ryotayama** [comment]
問合せ385も同件✍️

**Comment by sugartarou** [comment]
https://developer.android.com/reference/androidx/media/session/MediaButtonReceiver

**Comment by sugartarou** [comment]
公式によると、MediaSessionを使ってるのであればonStartCommandでMediaButtonReceiverと紐づけてしまえばMediaSessionCompat.Callbackと紐づいてくれるみたい。
```
private MediaSessionCompat mMediaSessionCompat = ...;

public int onStartCommand(Intent intent, int flags, int startId) {
  MediaButtonReceiver.handleIntent(mMediaSessionCompat, intent);
  return super.onStartCommand(intent, flags, startId);
}
```

ただ、はやえもんはAndroid13（SDK 33）以降でのみMediaSessionCompatを使っているのでAndroid 12以前はMediaButtonReceiverを直接オーバーライドしたほうが実装影響少なさそう。
```
        if (Build.VERSION.SDK_INT >= 33) {
            mediaSession = new MediaSessionCompat(this, "MediaSessionTag");

```

**Comment by sugartarou** [comment]
単純にMediaButtonReceiverを使うとAndroid13以降でMediaSessionの処理と競合してバグることがわかった。
Android12以前に絞ってMediaButtonReceiverをregisterReceiverするとかできないかな。。

**Comment by sugartarou** [comment]
古そうだけどこれを見てみる
https://youtu.be/FBC1FgWe5X4?si=Pg1ZL3uePSUaCREW

**Comment by sugartarou** [comment]
単純にMainActivityのonKeyDownに追加してみれば実は動くのでは。。。
```java
    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {

        if (keyCode == KeyEvent.KEYCODE_MEDIA_PLAY || keyCode == KeyEvent.KEYCODE_MEDIA_PAUSE || keyCode == KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE) {
            PlaylistFragment.onPlayBtnClick();
            return true;
        }
        if (keyCode == KeyEvent.KEYCODE_MEDIA_REWIND) {
            PlaylistFragment.onRewindBtnClick();
            return true;
        }
        if (keyCode == KeyEvent.KEYCODE_MEDIA_NEXT) {
            PlaylistFragment.onForwardBtnClick();
            return true;
        }
```

**Comment by ryotayama** [comment]
いったんonKeyDownの方試してみたけど動かず✍️

**Comment by ryotayama** [comment]
onHandleIntetの方も動かず✍️
やっぱり根深い話になるのかな…！

**Comment by sugartarou** [comment]
ぐぬぬ…ダメでしたか〜
intent-filterの記載をマニフェストにしとかないといけないとかある気がするので
手元の端末と有線イヤホンでとりあえず確認してみます。

**Comment by ryotayama** [comment]
「139-MediaBrowserお試し」、実機のAndroid 13環境で試してみたところうまくいってそう…！

◆アプリを起動
①再生ボタンをタップし、再生開始
②Bluetoothイヤホンの再生／一時停止ボタンを押す→一時停止
③再度、再生／一時停止ボタンを押す→再開
④再度、再生／一時停止ボタンを押す→一時停止
⑤再度、再生／一時停止ボタンを押す→再開

◆アプリをバックグラウンドにする
①Bluetoothイヤホンの再生／一時停止ボタンを押す→一時停止
②再度、再生／一時停止ボタンを押す→再開
③再度、再生／一時停止ボタンを押す→一時停止
④再度、再生／一時停止ボタンを押す→再開
