### ISSUE TITLE
ABループ画面の罫線を追加してほしい

### ISSUE THREAD

**Issue by UmeboshiKantaro** [ryotayama/Hayaemon_Android#140]
Android ver. 1.71

ABループ画面の罫線がないので追加してほしいです！

（つけたらストア用のスクリーンショットを差し替えるので！）

![Image](https://i.imgur.com/QTRJSEG.jpg)

**Comment by ryotayama** [comment]
対応しましたー！
![dpxb65yu4aa3t7z](https://user-images.githubusercontent.com/6075785/47133945-e10efe00-d2e5-11e8-8760-8783810fa87a.jpg)
