### ISSUE TITLE
｢エフェクトの設定保持を解除｣してからタスクキルをしても解除されていない

### ISSUE THREAD

**Issue by guxtuti-raven** [ryotayama/Hayaemon_Android#145]
Ver. 1.74

関連ツイート
https://twitter.com/recarendraven/status/1057240469980119041
エフェクトの設定保持を解除後、2分程経った後にタスクキルをしても解除されていない

**Comment by arigayas** [comment]
https://twitter.com/recarendraven/status/1057241819644194821

リリース版で再現可能

0. 事前にロックした状態でタスクキル
1. エフェクトの設定保持を解除をタップして1分待機
2. 再生してからいろいろごちゃごちゃいじる
3. タスクキル
4. 再起動
5. ダメだった(´･ω･｀)

@guxtuti-raven さんのツイートをなんとなく転載。
