### ISSUE TITLE
Bluetoothイヤホン切断時に再生を止めてほしい

### ISSUE THREAD

**Issue by mikuta0407** [ryotayama/Hayaemon_Android#156]
iOSだとイヤホンを抜いたり、BTイヤホンを切断すると再生が止まるのですが、Android版だと再生されたままになってしまっています
爆音テロや電池消費を抑えるという意味でも、対応していただけると幸いです

**Comment by arigayas** [comment]
クローズになっているけど、重複？
#138 イヤホンを抜いたら再生が止まるようにしてほしい

あ、#138はイヤホンジャックから抜き差しだけに対応したって事かな？

**Comment by arigayas** [comment]
タイトルを変えました。

**Comment by sugartarou** [comment]
> 突然の大音量再生の防止
別の方法で音楽を楽しむには、 Android デバイスを管理しています。ほとんどのデバイスにはスピーカーが内蔵されており、 Bluetooth 接続や Bluetooth 対応の Bluetooth 対応ヘッドセットも A2DP オーディオ。
ヘッドセットを外したり Bluetooth デバイスの接続を解除したりすると、音声ストリームは 内蔵スピーカーへのルートを自動的に変更できます。高音で音楽を聴いている場合 不自然な点もあるでしょう
ユーザーは通常、画面上で再生できる音楽プレーヤーを含むアプリを期待します コントロールを使用して再生を一時停止します。その他のアプリ（ゲームなど） 再生を続行できます。ユーザーは デバイスのハードウェア コントロールによって制御されます。
音声出力が内蔵スピーカーに切り替わると、システムが [ACTION_AUDIO_BECOMING_NOISY](https://developer.android.com/reference/android/media/AudioManager?hl=ja#ACTION_AUDIO_BECOMING_NOISY) をブロードキャストします。 使用します。[BroadcastReceiver](https://developer.android.com/reference/android/content/BroadcastReceiver?hl=ja) を作成する。 このインテントをリッスンします。レシーバは次のようになります。

https://developer.android.com/media/platform/output?hl=ja

https://github.com/ryotayama/Hayaemon_Android/commit/7ccd022e7aab0f69b0d2008020889918164b87fe でACTION_AUDIO_BECOMING_NOISYのintentを受け取るように実装してそうなので対応済み？

手元のPixel7a(A14)でBTイヤホン使って動確して問題なければクローズする。

**Comment by sugartarou** [comment]
> 手元のPixel7a(A14)でBTイヤホン使って動確して問題なければクローズする。
@ryotayama 
問題なかったのでクローズします。
