### ISSUE TITLE
広告削除に月額制を選べるようにしてほしい

### ISSUE THREAD

**Issue by yuri-regulus-25** [ryotayama/Hayaemon_Android#157]
お引っ越し元: https://github.com/ryotayama/Hayaemon/issues/317

## UmeboshiKantaro 2018.07.07
広告削除について、現在では買い切り方式の2000円しかないですが、
ユーザーによっては「高い」という声もたまにあるので、月額制も選択できるようになると嬉しいです。

現在、App Storeでの最低販売価格が120円なので、1年で1440円です。それだけでもう17ヶ月以上使う人にとっては買い切りのが得になります。

こうした計算ができるユーザーにとっては、2000円で足踏みしていた広告削除に踏み切る可能性があります。

また、結果的に高くついても、月120円の方が支払いやすい、というタイプのユーザーもいるかもしれないので、そういったニーズを満たすのも大事かなと思っています。

ぜひ一度ご検討ください(*･ω･)ﾉ

## ryotayama 2018.07.07
いいと思いまーす₍₍ (ง*ᐛ)ว ⁾⁾
画面的にはメニューの「広告を非表示にする」ってとこから２分岐する感じになるのかな？？

## UmeboshiKantaro 2018.07.07
「広告を非表示にする」
の次のアクションシートで
・月額120円
・買い切り2000円（←もう少し適切な表現があると嬉しい）
と選べるといいんでしょうか？？

ryotayama/Hayaemon/issues/275 とも関連付けしておきますね(*･ω･)ﾉ

## ryotayama 2018.07.07
金額出すの多言語化の観点からできるかどうかちょっと分かんないや！
また調べとく！

## UmeboshiKantaro 2018.07.07
あー、ドルとかになっちゃうからか…！
よろしくお願いします！

## ryotayama 2018.07.07
メモ。いけそうだね。
https://qiita.com/kyasusoft/items/28e48f60f46c32483061

## ryutaro 2018.07.08
買い切り=>ライフタイム

2ヶ月に1回とかも確かできたので(本当か？)
調整が必要ですね

## ryotayama 2018.07.08
個人的には月額120円はわるくないなぁと思った！

## ryutaro 2018.07.08
120円がというより ライフタイム2000円との兼ね合い？

**Comment by ryotayama** [comment]
Kyashアプリにて1,000円の支援をいただきました！🙏

**Comment by ryotayama** [comment]
# 残作業
- [ ] 買い切りプランの購入ボタンを押したら購入処理が走るようにする
- [ ] 買い切りプランの復元ボタンを押したら復元処理が走るようにする
- [ ] ウェブ上で月額プランのアイテムを仕込んでおく
- [ ] 月額プランの購入処理を実装
- [ ] 月額プランの復元処理を実装
- [ ] 月額プランの購入ボタンを押したら購入処理が走るようにする
- [ ] 月額プランの復元ボタンを押したら復元処理が走るようにする
- [ ] 月額プランの加入中かをチェックして広告を非表示にする処理を実装

**Comment by ryotayama** [comment]
- 定期購入について理解する - Play Console ヘルプ
https://support.google.com/googleplay/android-developer/answer/12154973?hl=ja

**Comment by ryotayama** [comment]
- About subscriptions | Google Play's billing system
https://developer.android.com/google/play/billing/subscriptions

**Comment by ryotayama** [comment]
- Integrate the Google Play Billing Library into your app
https://developer.android.com/google/play/billing/integrate

**Comment by ryotayama** [comment]
- 定期購入を作成、管理する
https://support.google.com/googleplay/android-developer/answer/12154973?hl=ja

**Comment by ryotayama** [comment]
- play-billing-samples
https://github.com/android/play-billing-samples/

**Comment by ryotayama** [comment]
テスト用の購入ダイアログを表示することに成功✍️
![Screenshot_20240305-105808](https://github.com/ryotayama/Hayaemon_Android/assets/6075785/3234ef37-8eef-4b71-85a3-4ceee5230c97)

**Comment by ryotayama** [comment]
買い切りで購入されている場合
　→広告消す
上記以外
　├サブスクで契約期間中に該当する場合
　│　→広告消す
　└上記以外
　　　→広告出てないなら出す

**Comment by ryotayama** [comment]
- Test your Google Play Billing Library integration
https://developer.android.com/google/play/billing/test
