### ISSUE TITLE
イコライザのカスタマイズ画面で左側のラベルが改行され、レイアウトが崩れている

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#21]
- 1.55.1（内部テスト版）
- Android 7.1.0 API 25 768x1280のエミュレータにて確認

イコライザのカスタマイズ画面で左側のラベルが改行され、レイアウトが崩れている為、修正します₍₍ (ง*ᐛ)ว ⁾⁾

![screenshot-2018-07-27_15 46 48 15](https://user-images.githubusercontent.com/6075785/43305934-707e87e0-91b4-11e8-91fb-ddeb653f6e49.png)

**Comment by ryotayama** [comment]
修正しました！
![after](https://user-images.githubusercontent.com/6075785/43625388-c53a0aca-9727-11e8-9067-15f9f3d16510.png)

**Comment by arigayas** [comment]
イコライザのラベルを一括付与しようとして失敗したので再度ラベルを付けました(汗)
