### ISSUE TITLE
イコライザ画面について、デフォルトでプリセットの「オフ」が選択されるようにしたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#227]
バージョン1.90

iOS版に合わせ、イコライザ画面について、デフォルトでプリセットの「オフ」が選択されるようにします！

**Comment by aafxaa** [comment]
関連会話の記録:

ハヤえもん android 1.92 ボーカルキャンセルはタップで有/無効を切替られるが、ボーカル抑制はタップで無効に出来ず。仕方なく「すべてのプリセットを初期化」で解除しているが、この使い方で合っているのでしょうか…?
https://twitter.com/cranberry_talks/status/1113830408745934849
↓
イコライザ画面をタップで無効化するのはいずれ対応予定です！
現状は一番上の「オフ」ってのを押すのが良いかと思います！
https://twitter.com/ryota_yama/status/1113830663755407361
↓
ハヤえもんAndroid版ver.1.95更新履歴
（15）イコライザのプリセットについて、デフォルトで「オフ」が選ばれるようにするとともに、選択中のプリセットをタップしたら選択を解除するように対応
http://hayaemon.jp/blog/archives/6660
↓
今更確認。2.03時点で、ボーカル抑制をタップで無効に出来るようになっていた。ありがとうございましたm(__)m
https://twitter.com/cranberry_talks/status/1130656673394073601
↓
おぉ、ご連絡忘れてましたね！
気づいてくれてありがとうございます！
https://twitter.com/ryota_yama/status/1130656854416060417
