### ISSUE TITLE
イコライザ間の隙間をiOS版に合わせたい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#23]
- Android 1.56.1（内部テスト版）

イコライザ間の隙間をiOS版に合わせます。

・音量と20Kの隙間を広くする
・各スライダーの隙間を広くする

◆Android版のスクショ
![Image](https://i.imgur.com/KRsCurI.jpg)

◆iOS版のスクショ
![Image](https://i.imgur.com/BCqJQ2H.jpg)

**Comment by ryotayama** [comment]
隙間を広げてみた！
![after2](https://user-images.githubusercontent.com/6075785/43626163-bcd85cf2-972b-11e8-8a5d-57374f63d45a.png)

**Comment by arigayas** [comment]
数値としては何から何に変化したんですか？

**Comment by ryotayama** [comment]
もともと隙間が0dpだったのを音量と20Kの間は16dp、それ以外のスライダー間は4dpだよ！

**Comment by arigayas** [comment]
わかりました！

**Comment by arigayas** [comment]
イコライザのラベルを一括付与しようとして失敗したので再度ラベルを付けました(汗)
