### ISSUE TITLE
アートワークが飛び出してしまう

### ISSUE THREAD

**Issue by Yakijake** [ryotayama/Hayaemon_Android#234]
https://mobile.twitter.com/UmeboshiKantaro/status/1121938230432026624

**Comment by arigayas** [comment]
うめさんのツイートからスクリーンショットを転載します。
![D5Hs3ybUcAE7753](https://user-images.githubusercontent.com/11251874/57134611-a5e79e80-6de1-11e9-94a8-442564c526e5.jpg)
