### ISSUE TITLE
非アクティブのグレーの部分がiOSと比べると暗い

### ISSUE THREAD

**Issue by Yakijake** [ryotayama/Hayaemon_Android#235]
https://mobile.twitter.com/UmeboshiKantaro/status/1121525405662322688

**Comment by arigayas** [comment]
うめさんのツイートからスクリーンショットを切り抜きました。

![D5B1aSoU0AANlSx](https://user-images.githubusercontent.com/11251874/57135399-358e4c80-6de4-11e9-8006-9cedb3978888.jpg)
