### ISSUE TITLE
[要望]ファイラーアプリから音声を直接ハヤえもんで開けるようにしてほしい

### ISSUE THREAD

**Issue by aafxaa** [ryotayama/Hayaemon_Android#236]
ハヤえもん android 2.00 要望。ファイラーアプリでmp3を選んだ時の選択肢に、ハヤえもんも出てほしい…m(__)m https://mobile.twitter.com/cranberry_talks/status/1124233820247511042

**Comment by aafxaa** [comment]
[fileopen.txt](https://github.com/ryotayama/Hayaemon_Android/files/3187039/fileopen.txt)
自分の環境での挙動。
使ってるファイラー「ファイルマネージャー」の挙動がちょっと変わっている。
シャープの「コンテンツマネージャー」の挙動がこのなかではまとも。
ファイラーの実装に因るのか?

**Comment by aafxaa** [comment]
@metabo55さんのファイラー知りたい…
https://twitter.com/ryota_yama/status/1128898257118044161

**Comment by metabo55** [comment]
メールに気付かず遅くなりました。
android7.0 標準搭載のファイルマネージャでためしました。
普段使いのX-plore では、エラー終了でハヤえもんに取り込めませんでした

**Comment by aafxaa** [comment]
metabo55さん、ありがとうございますm(_ _)m

家人の環境が機種:SH-04H、Android 7.0ですが、ファイルマネージャが見つかりませんでしたorz
metabo55さんの機種はシャープ以外のタブレットなのでしょうか…?

X-ploreのエラー終了の件は↓と同じみたいですね…
https://twitter.com/cranberry_talks/status/1129163264858894336

**Comment by aafxaa** [comment]
[fileopen.txt](https://github.com/ryotayama/Hayaemon_Android/files/3192180/fileopen.txt)
自分の環境での挙動(X-plore追加、不明確だった箇所追記)。

**Comment by metabo55** [comment]
確かにX-ploreの挙動は一緒ですね。
機種はタブレット（LG : LGT31）です

**Comment by aafxaa** [comment]
![無題89](https://user-images.githubusercontent.com/50232313/57961114-ccf8b100-7947-11e9-856f-e6947bae5c9f.jpg)
metabo55さん、ありがとうございますm(_ _)m

LGT31のファイルマネージャーって、このアイコンのアプリでしょうか?

**Comment by metabo55** [comment]
LGT31のファイルマネージャーはそのアイコンのアプリの事です。

**Comment by aafxaa** [comment]
[fileopen.txt](https://github.com/ryotayama/Hayaemon_Android/files/3193846/fileopen.txt
↑どこのファイルマネージャーか判るように書き直しました。

metabo55さん、ありがとうございますm(_ _)m

うーん、作者がどこのファイルマネージャーなんだろう…
「au ファイルマネージャー」「LG ファイルマネージャー」で検索したり、
google playでそれらしきアイコンを探したりしてみましたが見つけられませんでしたorz
インストールできれば「copied 0」の件も再現できそうだったのに…

しかしmetabo55さんの普段使いはX-plore、自分はファイルマネージャー(Flashlight + Clock)なので、
この２つでの今の不具合が直れば次善にはなるかな…?
情報が開発の助けになるといいんですが。

**Comment by metabo55** [comment]
android標準のファイル·マネージャだと思ってました。。。
LGT31に依存するアプリなら仕方無いですね。
使い勝手はX-ploreの方が機能が色々有って重宝してますがハヤえもんに正常取り込めるフェイラーアプリが在れば何でも構いませんし

**Comment by arigayas** [comment]
`機種依存` のラベルを付けようかと思ったけど、そうでもなくなってきました(汗)？

**Comment by aafxaa** [comment]
＞metabo55さん
LGT31をAndroid8に上げると、Android8のファイルアプリが使えると思うのですが、
上げられるのか判らないし、
上げて他のアプリが使えなくなったら困りますよね…

＞arigayasさん
「機種依存」にアプリ依存?が入るなら…(^^;

-----
〇ハヤえもんの再生リストに追加できる
・ファイル(アプリ、Android8から登場)
・Google ドライブ(アプリ)
・コンテンツマネージャー(シャープ製)

×ハヤえもんの再生リストに追加できない
・LGT31のファイルマネージャー→追加できるが曲名・アーティスト名がおかしい)
・ファイルマネージャー(Flashlight + Clock)→再生リストに追加されない(2.03)
・X-plore→ハヤえもん(2.03)停止
-----

**Comment by aafxaa** [comment]
＞metabo55さん
LGT31をAndroid8に上げると、Android8のファイルアプリが使えると思うのですが、
上げられるのか判らないし、
上げて他のアプリが使えなくなったら困りますよね…

＞arigayasさん
「機種依存」にアプリ依存?が入るなら…(^^;

-----
〇ハヤえもんの再生リストに追加できる
・ファイル(アプリ、Android8から登場)
・Google ドライブ(アプリ)
・コンテンツマネージャー(シャープ製)

×ハヤえもんの再生リストに追加できない
・LGT31のファイルマネージャー→追加できるが曲名・アーティスト名がおかしい)
・ファイルマネージャー(Flashlight + Clock)→再生リストに追加されない(2.03)
・X-plore→ハヤえもん(2.03)停止
-----

**Comment by arigayas** [comment]
@aafxaa さん
まとめ役お疲れさまです。

その機種だけ？にデフォルトでインストールされているファイルマネージャーアプリだから、
大きな意味で`機種依存`かなぁ？と思ったわけです。
機種依存 のラベルを付けるか否かを @ryotayama さんの意見も聞きたいかも。



> ・LGT31のファイルマネージャー→追加できるが曲名・アーティスト名がおかしい)

どのようにおかしいのか書くと良太さんが解決しやすいと思います。

_もしかすると、それぞれのファイルマネージャー用にissue登録することになるかもしれない？_

**Comment by aafxaa** [comment]
とりあえずこうですかね?

・LGT31のファイルマネージャー→追加できるが曲名・アーティスト名がおかしい)
→曲名:「copied0」(0は任意の数字)になる
　アーティスト名：「<不明なアーティスト>」になる
https://twitter.com/metabo55/status/1128892158205878272

**Comment by arigayas** [comment]
>> ・LGT31のファイルマネージャー→追加できるが曲名・アーティスト名がおかしい)

>→曲名:「copied0」(0は任意の数字)になる
>　アーティスト名：「<不明なアーティスト>」になる

なるほど。
![sD6qhbyaU0AAEJz2](https://user-images.githubusercontent.com/11251874/57969408-8770ce00-79b1-11e9-9922-f306701078e5.jpg)

**Comment by metabo55** [comment]
別なフェイラーアプリ(asus ファイルマネージャー)を試してみました。https://play.google.com/store/apps/details?id=com.asus.filemanager&hl=ja
結果はLGT31標準ファイルマネージャと全く一緒でした。
なので、アプリには依存していないかも？
一先ず報告マデ

**Comment by aafxaa** [comment]
[fileopen.txt](https://github.com/ryotayama/Hayaemon_Android/files/3194118/fileopen.txt)
↑asus ファイルマネージャー試したので追記しました。

なんとびっくり、自分の環境ではasusでハヤえもん登録成功しました。
metabo55さん:自分
----------------------
android7:android8
タブレット:スマホ
LGT31:SH-04H

あとは、使ってるmp3ファイルの違いでしょうか…?

**Comment by metabo55** [comment]
色々と確認頂き有難う御座います
なるほど同じアプリで問題無い！、となると。。。
試したmp3ファイルは、CDをリッピングしてさらハヤえもんでエクスポートしたファイルとmp3サンプルをダウンロードしたファイルですから、ハヤえもんにもファイルの選択では普通に読み込めてます。なのでLGT31の問題なのかも！？

**Comment by aafxaa** [comment]
自分の試したmp3は、Windows Media PlayerでCDから取り込んだだけのものでした。

metabo55さんのmp3も、曲名・アーティスト名の表示がおかしいだけで、
ハヤえもんの再生リストに追加はされるわけなので、
LGT31というより、mp3の曲名・アーティスト名の設定がどうなっているか気になります。
タグエディタとかで確認してみたいですね。

**Comment by ryotayama** [comment]
返信遅くなっちゃった！
大きな意味で機種依存で良いと思いまーす！
みんな細かく確認してくれてありがとう！

**Comment by aafxaa** [comment]
[ぶんぶんぶんの替え歌.zip](https://github.com/ryotayama/Hayaemon_Android/files/3203280/default.zip)
↑サンプルmp3入りzip(曲名:ぶんぶんぶんの替え歌、アーティスト名:白音リノ、サイズ390KB)

> arigayasさん
> もしかすると、それぞれのファイルマネージャー用にissue登録することになるかもしれない？

issue分けるとしたら案:
1.ファイルマネージャー(Flashlight + Clock)→再生リストに追加されない(2.03)
2.X-ploreから再生リストに追加しようとするとハヤえもん(2.03)停止
　https://twitter.com/cranberry_talks/status/1129163264858894336
3.LGT31のファイルマネージャーの件
　→曲名:「copied0」(0は任意の数字)になる
　　アーティスト名：「<不明なアーティスト>」になる

　metabo55さんに、
　LGT31のファイルマネージャーから、↑に貼ったサンプルmp3をハヤえもん登録して、
　曲名とアーティスト名が表示されるか試してもらう
　→正しく表示された場合:
　　LGT31のファイルマネージャーはハヤえもん登録に使えるということなので、
　　曲名・アーティスト名がおかしくなるmp3を作ったアプリ側で対処してもらう。
　→正しく表示されない場合:
　　LGT31のファイルマネージャーから再生リストに追加すると曲名とアーティスト名がおかしい(2.03)
　　→LGT31のファイルマネージャーを入手するのは難しいので、
　　　metabo55さんのご協力を得ながらの対応になる

**Comment by aafxaa** [comment]
[fileopen.txt](https://github.com/ryotayama/Hayaemon_Android/files/3244425/fileopen.txt)
↑ファイルマネージャー(Flashlight + Clock)、X-plore、ファイルマネージャー(ZenUI,ASUS)に追記

＞1.ファイルマネージャー(Flashlight + Clock)→再生リストに追加されない(2.03)
2.04でも追加されませんが、
「アプリで開く」ではなく「共有」を使うと追加されることが判りました。
とりあえず自分はこれで使おうと思います。

＞2.X-ploreから再生リストに追加しようとするとハヤえもん(2.03)停止
ハヤえもん android 2.04とX-plore 4.14.20(両方とも最新)で試したら直っていました。
https://twitter.com/cranberry_talks/status/1135032049222397953
metabo55さんの普段使いはX-ploreなので、これで行けるかと思います。

＞3.LGT31のファイルマネージャーの件
前回コメントのままです。
metabo55さんのご意向次第でissue登録になるかと。

「アプリで開く」ではなく「共有」だとうまくいくというのが、個人的には謎なんですが、
とりあえず自分の調査はここまでにします。お付き合いありがとうございました。

**Comment by aafxaa** [comment]
関連会話の記録:

ハヤえもん android 2.00 要望。ファイラーアプリでmp3を選んだ時の選択肢に、ハヤえもんも出てほしい…m(＿)m
https://twitter.com/cranberry_talks/status/1124233820247511042
↓
ありがとうございます！
ＯＫです、対応します！
https://twitter.com/ryota_yama/status/1124234616905187328
