### ISSUE TITLE
一部のMP4ファイルが再生できない

### ISSUE THREAD

**Issue by aafxaa** [ryotayama/Hayaemon_Android#240]
別の音楽再生アプリでは再生できていたmp4のファイルがはやえもんで再生できません。再生リストには追加できるのですが、タップしても音楽がはじまりません。再生できるmp4ファイルもあります。解決案があれば教えてください。Androidです。
https://mobile.twitter.com/konkonyuuhaku/status/1123756270639570949

**Comment by arigayas** [comment]
再生できなかった(＝デコーダが未対応)らエラーメッセージ「未対応のmp4形式です」等が出ると
ユーザにはわかりやすいと思います。

**Comment by ryotayama** [comment]
そうだね、ありさんありがとー٩( ᐛ )و
今回の件については、再生できない事自体がバグなのかもしれないからもうちょっと調べるけど、それとは別の問題としてエラーメッセージは出した方がいいかも！

**Comment by arigayas** [comment]
> 再生できなかった(＝デコーダが未対応)らエラーメッセージ「未対応のmp4形式です」

新たにこれでissue登録しますか？

**Comment by ryotayama** [comment]
ありさん、ありがとー！　登録しといた！٩( ᐛ )و

**Comment by arigayas** [comment]
登録を提案したのにissue登録してもらって何か申し訳ないっす(汗)
