### ISSUE TITLE
イコライザ画面の「プリセット」という言葉を「テンプレート」に変更してほしい

### ISSUE THREAD

**Issue by aafxaa** [ryotayama/Hayaemon_Android#243]
イコライザ画面の「プリセット」って言葉を「テンプレート」に変える対応、iOS版の方では対応したんだけど、Android版の方未対応だね！　また対応しとこーっと！٩( ᐛ )و
https://twitter.com/ryota_yama/status/1130750735807729664

iOS版側:https://github.com/ryotayama/Hayaemon_iOS/issues/275

**Comment by aafxaa** [comment]
どーでもいい話ですが、Android版の「イコライザ」ラベルは濃い緑系、iOS版のは黄色系でした^_^;

**Comment by arigayas** [comment]
> Android版の「イコライザ」ラベルは濃い緑系、iOS版のは黄色系でした^_^;

ラベルの色の指定は @UmeboshiKantaro さんがやっているから取りかかるまではバラバラです^_^;

**Comment by arigayas** [comment]
ラベルの色の指定で @UmeboshiKantaro さんが悩まれているので
とりあえずiOS側の色にラベルを合わせました。
