### ISSUE TITLE
曲の追加画面について、前回の表示設定を記憶しておいてほしい

### ISSUE THREAD

**Issue by ny-yamana** [ryotayama/Hayaemon_Android#244]
ハヤえもん android 2.00 要望。曲追加のダイアログで一度リスト表示?を選んだら、次にダイアログを表示した時も最初からリスト表示希望。アーティスト名、曲名、アルバム名とも長いのでm(__)m
https://mobile.twitter.com/cranberry_talks/status/1123750358948483073

**Comment by aafxaa** [comment]
関連会話の記録:

ハヤえもん android 2.00 要望。曲追加のダイアログで一度リスト表示?を選んだら、次にダイアログを表示した時も最初からリスト表示希望。アーティスト名、曲名、アルバム名とも長いのでm(__)m
https://twitter.com/cranberry_talks/status/1123750358948483073
↓
おぉ、なるほど！
ありがとうございます！
それも実現方法から調べてみまーす！
https://twitter.com/ryota_yama/status/1123814986906841093

**Comment by sugartarou** [comment]
ファイラーアプリ側の仕様（使うファイラーアプリによっても変わる）なので、ハヤえもん側から制御できない。
実現できないので、クローズ。
