### ISSUE TITLE
「アートワークを変更」→「ギャラリーから設定」のアイコンをiOS版と同じにしたい

### ISSUE THREAD

**Issue by aafxaa** [ryotayama/Hayaemon_Android#248]
ハヤえもん android 2.04 要望「アートワークを変更」→「ギャラリーから設定」のアイコンをiOS版と同じにしたい。
これでフィルムアイコン→動画、天体と山アイコン→画像、となるのでは…?
https://mobile.twitter.com/cranberry_talks/status/1134286213181927424

**Comment by arigayas** [comment]
### ハヤえもん android 2.04
![resized_Android_D73LSxqVUAAm3Wm](https://user-images.githubusercontent.com/11251874/58702757-a45dc600-83e1-11e9-938c-7c97b9947113.jpg)

### iOS版
![resized_iPad_D73LS2aUYAA45ur](https://user-images.githubusercontent.com/11251874/58702766-aaec3d80-83e1-11e9-9dad-46701d039601.jpg)
