### ISSUE TITLE
録音したファイルをエクスポートしようとするとアプリが落ちる

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#274]
https://twitter.com/liflil/status/1140121803781574656

**Comment by arigayas** [comment]
Android自体のバージョンも聞くのもヒントになるかもしれませんね。

**Comment by ryotayama** [comment]
ありさん、ありがとー！
Android 8.0.0だってさ٩( ᐛ )و

**Comment by sugartarou** [comment]
かなり古いのと、最近のお問い合わせフォームには特に来ていない話なので、改善していると見なしてクローズ。
