### ISSUE TITLE
タスク一覧のヘッダーの背景色を白にしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#278]
https://twitter.com/umeboshikantaro/status/1141335212065873921

**Comment by arigayas** [comment]
![resized_D9bWUt9U0AErNNn](https://user-images.githubusercontent.com/11251874/59817033-488bba80-9359-11e9-8b76-52b5420e9128.jpg)

**Comment by ryotayama** [comment]
ありさん、いつもありがとう(*T-T)
