### ISSUE TITLE
ステータスバーの下に罫線が欲しい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#279]
https://twitter.com/ryota_yama/status/1141553191420456960

**Comment by arigayas** [comment]
### 変更前のスクリーンショット
![resized_D9ecku5U0AAYEm4](https://user-images.githubusercontent.com/11251874/59890907-0bcdcb00-940e-11e9-8e1c-0a4a48024a8b.jpg)

![resized_D9ecku7U0AAAbPC](https://user-images.githubusercontent.com/11251874/59890914-0ec8bb80-940e-11e9-92a2-f885ec2f8838.jpg)


### 変更後のスクリーンショット
![resized_D9egXsTUcAAKQWe](https://user-images.githubusercontent.com/11251874/59891029-839bf580-940e-11e9-8029-2ddbbb8e9d81.jpg)
![resized_D9egY7IUIAAuigy](https://user-images.githubusercontent.com/11251874/59891032-8860a980-940e-11e9-8266-12b6ecaf73c8.jpg)

![resized_D9egYcCVUAEZO6S](https://user-images.githubusercontent.com/11251874/59891034-8c8cc700-940e-11e9-81d8-14552d3510ae.jpg)

![resized_D9egZZ5UIAY8IRo](https://user-images.githubusercontent.com/11251874/59891036-8eef2100-940e-11e9-9267-3bd81c5db6f0.jpg)

**Comment by ryotayama** [comment]
ありさん、ありがとうありがとう(ノ_ _)ノ
