### ISSUE TITLE
オートメーションが出来るようになってほしい

### ISSUE THREAD

**Issue by Otomopon** [ryotayama/Hayaemon_Android#285]
ABループ画面でマーカーを挿入できて、ハヤえもんのエフェクトのカスタマイズとかで
徐々にパラメーターが時間に比例して等速度移動したりすると嬉しい…かもです

**Comment by sugartarou** [comment]
だんだん○○系のエフェクトが当てはまると思います。
#341 #331 で対応済みだと思うのでクローズしまっす。

追加要望あれば、具体的に欲しい機能を書いたうえでリオープンするか別issue起票してください～
