### ISSUE TITLE
録音を右上のマイクボタンで止めた時にゼロ秒のデータができてしまう

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#295]
https://twitter.com/cncrave/status/1150386694954217474

**Comment by arigayas** [comment]
### ユーザーさんのコメント：
録音の停止のときに、四角の停止マークではなくて、
もう一度マイクマークの録音ボタンに触ると録音できているかのように手順が進むけど録音はされない。
ゼロ秒で新規録音で増えてしまう。

単純に紛らわしいかと。 録音している環境かどうかハッキリさせて止める時もわかりやすく。
