### ISSUE TITLE
Android 5.0以上の環境で、ステータスバーのアイコンが真っ白の四角に

### ISSUE THREAD

**Issue by aafxaa** [ryotayama/Hayaemon_Android#301]
関連会話の記録:

ハヤえもん android 1.93 再生すると白い角丸四角が左上に出るのですが、これは…?
https://twitter.com/cranberry_talks/status/1114494670350872576
↓
本来アイコン画像が出るところですね！
何か出ないパターンがあるのかもしれません！
確認してみますね！
https://twitter.com/ryota_yama/status/1114502685821030400
↓
Android版ver.1.95更新履歴
（24）Android 5.0以上の環境で、ステータスバーのアイコンが真っ白の四角になってしまっていた為、アイコン画像を差し替え
http://hayaemon.jp/blog/archives/6660
↓
ハヤえもん android 1.95 「らしい」アイコンありがとうございましたm(__)m
https://twitter.com/cranberry_talks/status/1118130503113162752
↓
おぉ、ちゃんと表示されましたね！
ありがとうございます！
https://twitter.com/ryota_yama/status/1118277656082911232

クローズ可能。

**Comment by ryotayama** [comment]
ありがとー、クロースします！👍
