### ISSUE TITLE
一部の環境で再生中画面のリピート／シャッフルボタンの表示が切れていた

### ISSUE THREAD

**Issue by aafxaa** [ryotayama/Hayaemon_Android#302]
関連会話の記録:

ハヤえもん android 1.93 再生した時、再生ボタンの下の2つのボタン?が欠けるのですが、直りますか?
https://twitter.com/cranberry_talks/status/1114495196740358144
↓
おぉ、ありがとうございます！
確認します！
https://twitter.com/ryota_yama/status/1114502785561587712
↓
ハヤえもん android 1.95 こちらのボタン欠けはまだ…というか、上にも同じボタンがあることに気付いた…下のボタンの必要性って…?
https://twitter.com/cranberry_talks/status/1118135995566833664
↓
大きな画面だと上の方のボタンって押しにくいので、下の方にも配置されているってのが大事だったりするんですよねー！
ちなみにボタン欠け、先ほど修正したので次のリリースで直ります！
https://twitter.com/ryota_yama/status/1118277955413667840
↓
Android版ver.1.96更新履歴
（２）一部の環境で再生中画面のリピート／シャッフルボタンの表示が切れていたのを修正
http://hayaemon.jp/blog/archives/6663
↓
ハヤえもん android 1.96 ボタンok、ありがとうございましたm(__)m なるほど、大きな画面対策ですか…φ(.. )
https://twitter.com/cranberry_talks/status/1118522932811026432
↓
おぉ、直りましたね！
良かったですー！
また気になるとことかあったら、いつでも教えてくださいね！
https://twitter.com/ryota_yama/status/1118654219110600707

クローズ可能。

**Comment by ryotayama** [comment]
クランベリーさん、ありがとー！
クローズします！👍
