### ISSUE TITLE
リバーブなどの一覧表示があるエフェクトを選んでから、再生周波数などの一覧表示がないエフェクトを選ぶと画面表示がおかしくなる

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#306]
https://twitter.com/arigayas/status/1158731874132361216?s=20
NoxPlayerd でハヤえもん 2.10を触ってみたんですが「エフェクト」の「再生周波数」のオフの位置がおかしいのかな？　”再”って文字が見えてる
![EBSj6eeUcAAhR_e](https://user-images.githubusercontent.com/6075785/62622497-705ece00-b959-11e9-8c5e-bbf877471fca.jpeg)

環境：NoxPlayer + ハヤえもん 2.10
「エフェクト」の「だんだん速く」と「だんだん遅く」のオフの位置がおかしいのかな？　”指”って文字が見えてる
![EBSmLl9UcAU97BK](https://user-images.githubusercontent.com/6075785/62622523-840a3480-b959-11e9-905e-5b631bee71bf.jpeg)
![EBSmVCfU4AA9-kS](https://user-images.githubusercontent.com/6075785/62622530-879dbb80-b959-11e9-9cad-31d245d1b0e1.jpeg)

環境：NoxPlayer + ハヤえもん 2.10 「エフェクト」の「メトロノーム」のオフの位置がおかしいのかな？　”BI”って文字が見えてる

こちらからは以上です。エミュレータのせいかもなので確認のためにリプライを送りました。
![EBSm1mQUEAEiig1](https://user-images.githubusercontent.com/6075785/62622542-92585080-b959-11e9-8c67-96816d183c91.jpeg)

ありさん、ありがとう٩( ᐛ )و
確認してみるね！👍

確認した結果を教えて欲しいです…。

確認してみた！

再生周波数、パン、だんだん速く、だんだん遅く、メトロノーム
で表示がおかしかったよ！

ありさんありがとう〜！
![EBXcZAIUwAEfRYz](https://user-images.githubusercontent.com/6075785/62622594-abf99800-b959-11e9-8b40-8c79e959b965.jpeg)
![EBXcZP_UYAEw9WQ](https://user-images.githubusercontent.com/6075785/62622601-b025b580-b959-11e9-87ab-490c4c1345a4.jpeg)
![EBXcZbtUEAIAUBl](https://user-images.githubusercontent.com/6075785/62622604-b3b93c80-b959-11e9-8f0b-e60182ef1f2a.jpeg)
![EBXcZm9U4AA4ddh](https://user-images.githubusercontent.com/6075785/62622607-b6b42d00-b959-11e9-8273-e143d156b464.jpeg)

**Comment by arigayas** [comment]
再現しないとリプライを良太さんに送ったら、

https://twitter.com/ryota_yama/status/1159078379699630080
**リバーブを選んで**から、
**再生周波数を選んだ**ら起きたよ！

再現しました！(とリプライしました。)
