### ISSUE TITLE
曲を再生する時にアプリが落ちるケースがある

### ISSUE THREAD

**Issue by aafxaa** [ryotayama/Hayaemon_Android#314]
関連会話の記録:

ハヤえもん android 2.03 X-plore 4.14.09 ファイラX-ploreでSDカード内mp3を1つ長押し選択し「他のアプリで開く」でハヤえもんを選ぶとハヤえもんが停止する(T_T)
https://twitter.com/cranberry_talks/status/1129163264858894336
↓
クランベリーさん、ありがとうございます！
試してみますね！
https://twitter.com/ryota_yama/status/1129164342694252544
↓
下記issueでmetabo55さんから「X-ploreではエラー終了でハヤえもんに取り込めない」とのコメント有り(2019/5/17)
https://github.com/ryotayama/Hayaemon_Android/issues/236
↓
これですが、ハヤえもん android 2.04とX-plore 4.14.20(両方とも最新)で試したら直っていました。ありがとうございました…かな?
https://twitter.com/cranberry_talks/status/1135032049222397953
↓
あー、あれか！　直した！
ありがとー、Closeしとくね
https://twitter.com/ryota_yama/status/1135032538714365952
↓
ハヤえもんAndroid版、エフェクト画面への「コーラス／フランジャー」「ディストーション」「コンプレッサー」のカスタマイズ機能追加を含む、５点の対応を行ったver.2.04をリリース！（ハヤえもんAndroid版ver.2.04更新履歴）
（５）曲を再生する時にアプリが落ちるケースがあったのを修正
http://hayaemon.jp/blog/archives/6883
↓
あれ、、そもそも未登録だったごめん！
https://twitter.com/ryota_yama/status/1135032763529084928

close可能。

**Comment by ryotayama** [comment]
Closeします！
