### ISSUE TITLE
「動画で保存」で出来たmp4がtwitterに投稿出来ない

### ISSUE THREAD

**Issue by aafxaa** [ryotayama/Hayaemon_Android#315]
ハヤえもん Android ver.2.09 Android 8.0.0 SH-04H
「動画で保存」で出来上がったmp4がtwitterに投稿出来ませんでした(互換性が無いと出る)。
過去に投稿していた方がいたような気がするのですが、
元々twitterに投稿可能な動画を作る仕様だったのか知りたいですm(_ _)m
https://twitter.com/cranberry_talks/status/1152617503274651649
↓
投稿可能な仕様で作ったつもりだったけど、おかしいなー！
こっちでも試してみるね！
https://twitter.com/ryota_yama/status/1152617896662556672

**Comment by aafxaa** [comment]
どうやら、今回出来た動画は
「Androidアプリで投稿可能」だが「ブラウザでの投稿条件を満たしていなかった」
模様。

 Twitterで動画を共有および視聴する方法
 https://help.twitter.com/ja/using-twitter/twitter-videos

別ツールで変換すればブラウザでも投稿出来るようになった。
ハヤえもんとしては、最低1パターンは投稿出来ているので問題無いのでは。
＝＝＝
Android2.16で動画として保存:
・AndroidのChromeで投稿→「互換性がありません」
・AndroidのChromeでTweetDeckから投稿→「Unknown error」「We could not upload」
・Androidのtwitterアプリで投稿→OK
・WindowsのEdgeで投稿→「互換性がありません」
・WindowsのEdgeでTweetDeckから投稿→「We could not upload」
・Windowsのtwitterアプリで投稿→「互換性がありません」

Twitter用に動画変換するやつ
https://cloth.moe/2016_twitter_convert/
過去版（安定）「Twitter用に動画変換するやつ20170101.zip」
で変換したもの:
・AndroidのChromeで投稿→OK
・AndroidのChromeでTweetDeckから投稿→OK
・Androidのtwitterアプリで投稿→(変換せずに出来てるので省略)
・WindowsのEdgeで投稿→OK
・WindowsのEdgeでTweetDeckから投稿→OK
・Windowsのtwitterアプリで投稿→OK
＝＝＝
参考:iOS3.53で動画として保存:
・iOSのSafariで投稿→OK
・iOSのSafariでTweetDeckから投稿→「selected file is not an image」
・iOSのtwitterアプリで投稿→iPad3(iOS9.3.5)なのでアプリ入らず

Twitter用に動画変換するやつ
https://cloth.moe/2016_twitter_convert/
過去版（安定）「Twitter用に動画変換するやつ20170101.zip」
で変換したもの:
・iOSのSafariで投稿→(変換せずに出来てるので省略)
・iOSのSafariでTweetDeckから投稿→OK
・iOSのtwitterアプリで投稿→iPad3(iOS9.3.5)なのでアプリ入らず

**Comment by ryotayama** [comment]
@aafxaa クランベリーさん、ありがとー！🙏
Twitterアプリでは投稿可能なのでCloseします！
今後、「ブラウザからでも投稿できるようにしてほしい！」というリクエストが多かったら別途対応を考えます！
