### ISSUE TITLE
不具合報告のリンクから遷移するツイート画面で各種情報が自動で補完されるようにしてほしい

### ISSUE THREAD

**Issue by aafxaa** [ryotayama/Hayaemon_Android#316]
不具合報告のリンクから遷移するツイート画面で各種情報が自動で補完されるようにしてほしい。
https://github.com/ryotayama/Hayaemon_iOS/issues/170
＝＝＝
ハヤえもんAndroid2.14 Android8.0.0 SH-04H
不具合報告メニューを使うと、りょーたさんのtwitterサイトまでは自動で行くが、バージョン情報のデフォルト入力まで行かない。
これiOSのissueしか見つけられなかったんですが、Androidはまだでしたっけ?
https://twitter.com/cranberry_talks/status/1165223228593192961
↓
それAndroid版は未導入だった！
簡単にできそうだから、早めにやろーかな！
https://twitter.com/ryota_yama/status/1165225087294787584

**Comment by ryotayama** [comment]
対応した！　バージョン2.27でリリース予定！
