### ISSUE TITLE
一部の環境で録音ができなくなっていた

### ISSUE THREAD

**Issue by aafxaa** [ryotayama/Hayaemon_Android#351]
Android2.27 Android8.0.0 SH-04H
録音出来ない(イヤホン不使用)
録音後、端末最大音量、イコライザ最大音量にしても音が聞こえない。
ループ画面に波形が無い。
権限はマイクが付いている。
https://twitter.com/cranberry_talks/status/1264342712787980289

**Comment by aafxaa** [comment]
↓
クランベリーさん、ありがとう
わお、それはビックリ！
いま手元の端末（ハヤえもん 2.27、Android 4.4.2）で試してみたけど、再現できなかった！（正常に録音された）
引き続き確認してみるね
https://twitter.com/ryota_yama/status/1264344485162409989
↓
Android ver.2.27 Android 8.0.0 SH-04H
今クリーンインストールして、即録音ボタン押してマイク権限許可して録音してみましたが、
やっぱり聞こえず波形無しでしたorz
https://twitter.com/cranberry_talks/status/1264437322763825152
↓
そっかそっか
ありがとー！
https://twitter.com/ryota_yama/status/1264437629648437248
↓
Android2.31 Android 8.0.0 SH-04H
iOS3.83 iOS9.3.5 iPad3,1
確認なんですが、
ハヤえもんで録音した音を再生した際、ループ画面に切り替えても波形が表示されませんが、
これは仕様ですよね?
https://twitter.com/cranberry_talks/status/1279643783416516609
↓
クランベリーさん、ありがとー！
それ再現できてないんだよねー！
https://twitter.com/ryota_yama/status/1279644263366574081
↓
今、
Android2.31→録音聞こえず波形も出ない
iOS3.83→録音出来るが波形出ない
なんです。
iOS3.83は録音出来るからOKと思ってたんですが、
波形出ないのはおかしいってことですか?
https://twitter.com/cranberry_talks/status/1279647375288500224
↓
うんうん、波形が出ないのが想定外…！
https://twitter.com/ryota_yama/status/1279647701102034945
↓
iOS3.83は録音時間増やしたら、8秒くらい再生したところで波形出始めました。
今までの録音時間が短すぎたみたいです。お騒がせしましたm(_ _)m
Android2.27～2.31で録音出来ないのがおかしいってことですね…
https://twitter.com/cranberry_talks/status/1279653049598799873
↓
Android Studioに古いソース落として、実機とPCを繋いで遡りました。
2019/07/15 2.09は録音/波形表示OK
2019/07/28 #296 対応は録音/波形表示OK
2019/07/28 #287 対応で録音/波形表示NG
2019/08/05 2.10は録音/波形表示NG
お手すきの際によろしくお願いしますm(_ _)m
https://twitter.com/cranberry_talks/status/1279743751317929984
↓
クランベリーさんありがとう！
めっちゃくちゃ助かる！
モノラルでしか録音できないデバイスでも一律ステレオとして録音しようとしてるのが
原因かも…！
もうちょっと追いかけてみるね！
https://twitter.com/ryota_yama/status/1279749521224785921

**Comment by aafxaa** [comment]
ハヤえもんAndroid開発版、一部の環境で録音できなくなっていたのを直しました
リリースまでもうしばらくお待ちくださいませ
https://twitter.com/ryota_yama/status/1283726050984210432
---
ハヤえもんAndroid最新版のアプデ申請をしました
更新内容
・モノラル音源の場合「動画として保存」で出力した動画がおかしいのを修正
・一部の環境で録音できないのを修正
・電池切れエフェクトが機能しないのを修正
・端末のサイズにより最適なサイズが適用されるアダプティブバナー広告に変更
https://twitter.com/ryota_yama/status/1284050618647064576
---
ハヤえもんAndroid最新版を本日リリースしました
更新内容
・「動画として保存」で出力した動画がおかしいケースを修正
・録音ができないケースを修正
・電池切れエフェクトが機能しないのを修正
・端末により最適なサイズが適用されるアダプティブバナー広告に変更
https://twitter.com/ryota_yama/status/1284103802753126401
---
2020/07/17 2.32リリース

**Comment by ryotayama** [comment]
Closeします！
