### ISSUE TITLE
通知エリアについて、再生中／一時停止中に関わらず一時停止ボタンが表示されるのを修正する

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#388]
問合せ番号；52、180、183

**Comment by sugartarou** [comment]
関連：MediaControls
#123 #139

**Comment by sugartarou** [comment]
iconがdeprecatedなところが気になる。
![image](https://github.com/ryotayama/Hayaemon_Android/assets/32073583/5b6dc838-dd5f-4c63-9447-1aa77eb6ce99)
deprecatedの説明読むとgetIconCompatを代わりに使えって出てくるけどgetterしか解放されてないところを見ると、setterが死んでてiconにセットしても差し替えられてないとかでは？
![image](https://github.com/ryotayama/Hayaemon_Android/assets/32073583/431d1207-956a-4109-b425-5e3c1bf247e3)

.iconにこだわらず、actionPlayPauseをactionPlayとactionPauseに分けちゃえばサクっと直る気がする。

**Comment by sugartarou** [comment]
Pixel 6 + Android 11 の環境で不具合再現⇒改善を確認。

**Comment by sugartarou** [comment]
notificationManagerの取得は元々複数箇所で使う時だけやってるっぽいので、そのままにして、
関数化だけしておく
