### ISSUE TITLE
SDカードから曲が追加された場合、アプリ内の保存領域にデータをコピーして読み込むように対応する

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#389]
## 現状
- 端末内から追加→データへのリンクを保持
- 動画から追加→音声データをアプリ内の保存領域に保存
- URLから追加→ダウンロード後のデータをアプリ内の保存領域に保存

## 変更後
- 端末内から追加
  ＜SDカードから追加＞
  アプリ内の保存領域に保存
  ＜端末内のデータを追加＞
  データへのリンクを保持
- 動画から追加→音声データをアプリ内の保存領域に保存
- URLから追加→ダウンロード後のデータをアプリ内の保存領域に保存

**Comment by sugartarou** [comment]
■メモ
onActivityResultのrequestCode==1が曲追加のコールバック

**Comment by sugartarou** [comment]
Android StudioのエミュレータでSDカード使いたくて/mnt/sdcard配下にファイル置いてもなぜか内臓ストレージとして扱われてしまう．．
どうやって動作確認しよう

**Comment by sugartarou** [comment]
URIから曲データをアプリのローカルストレージにコピーする方法は以下でよさそう
```
Uri uriCopy = sActivity.copyFile(data.getData());
```

**Comment by sugartarou** [comment]
isExternalStorageRemovableはAPI level21からしか使えない
https://developer.android.com/reference/android/os/Environment#isExternalStorageRemovable(java.io.File)

それ以前は結構めんどくさそう。Javaのリフレクション使ってる。。
https://qiita.com/h_yama37/items/11b8658b2de9625200aa

**Comment by ryotayama** [comment]
GDPR対応でMinSdkVersionを21に変えるので問題無いです、ありがとう！👍
