### ISSUE TITLE
プロモーションコード使用時に広告非表示が適用されるように対応

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#396]

**Comment by ryotayama** [comment]
要件としては、１ヶ月分のプロモーションコードをプレゼントする予定なので、一度広告非表示になり、期限が切れたら広告が再表示されるように対応。

**Comment by sugartarou** [comment]
https://www.perplexity.ai/search/How-to-implement-HAjyKNqmSdGOU.HhGYBCBw
