### ISSUE TITLE
再生リストに並べ替え機能を追加する

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#41]
再生リストに並べ替え機能を追加します₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by ryotayama** [comment]
## 参考URL
### ItemTouchHelper | Android Developers
https://developer.android.com/reference/android/support/v7/widget/helper/ItemTouchHelper

**Comment by UmeboshiKantaro** [comment]
これって、Android端末では自分、「並べ替え」ってしたことないけど、形状は同じでいいのかな？？

あとサイズはどうしましょう？？

**Comment by ryotayama** [comment]
いろいろ調べた結果、Androidのリストビューでは標準での並べ替え機能の提供が無い関係で、開発者ごとに自由に実装してるってのが実態みたいだから、同じでいいかなーと思うけどどーかな？？

サイズは、30x30dp（以下６種類）でお願いします！！

- ldpi (0.75x)	@ 30.00dp	= 22.50px
- mdpi (1x)	@ 30.00dp	= 30.00px
- hdpi (1.5x)	@ 30.00dp	= 45.00px
- xhdpi (2x)	@ 30.00dp	= 60.00px
- xxhdpi (3x)	@ 30.00dp	= 90.00px
- xxxhdpi (4x)	@ 30.00dp	= 120.00px

**Comment by UmeboshiKantaro** [comment]
ありがとう🙏 では同一の形状で作成しますね。

関係ないけどこれ他のアイコンも同様のサイズ展開必要だよねぇ。。(；-ω-)ゞ

**Comment by ryotayama** [comment]
たしかに……！

iOS版の等倍率のやつ（後ろの@2xとか@3xとか付かないやつ）をベースに以下６展開が必要です！

このページ使うと算出してくれるから便利かも₍₍ (ง*ᐛ)ว ⁾⁾
http://labs.rampinteractive.co.uk/android_dp_px_calculator/

**Comment by UmeboshiKantaro** [comment]
了解です(o`･ω･)ゞ

**Comment by ryotayama** [comment]
対応した₍₍ (ง*ᐛ)ว ⁾⁾
![screenshot-2018-08-13_03 15 19 976](https://user-images.githubusercontent.com/6075785/44005427-709a2a34-9eae-11e8-97ea-f1d43cdf042e.png)
![screenshot-2018-08-13_03 15 29 827](https://user-images.githubusercontent.com/6075785/44005428-72dd9f92-9eae-11e8-8746-b407e3bbdc5f.png)
