### ISSUE TITLE
エフェクト画面に「メトロノーム」を追加する

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#67]
エフェクト画面に「メトロノーム」を追加します₍₍ (ง*ᐛ)ว ⁾⁾

**Comment by arigayas** [comment]
### 関連するissue

- ryotayama/Hayaemon/issues/414
- ryotayama/Hayaemon/issues/429
- ryotayama/Hayaemon/issues/431
- ryotayama/Hayaemon/issues/437

**Comment by ryotayama** [comment]
できた！
![dmikkf9u4aage_h](https://user-images.githubusercontent.com/6075785/45248663-0572d480-b34f-11e8-9f00-0839268f9e9a.jpg)
![dmikkk9u4aaxiac](https://user-images.githubusercontent.com/6075785/45248665-0ad01f00-b34f-11e8-8a44-614e5a7f5337.jpg)
