### ISSUE TITLE
「アプリ情報」画面がほしい。

### ISSUE THREAD

**Issue by arigayas** [ryotayama/Hayaemon_Android#8]
### 文字情報として

- ソフト名：ハヤえもん
- インストールされているバージョン情報：X.xx
- 作者名：　　_← iOS版では書いてないから削除かな？_
- 配布場所：　_← iOS版では書いてないから削除かな？_

### 画像として

- ロゴ

### 動作

- バージョン情報をクリップボードにコピーする機能。

が必要でしょうか？

### 関連するissue
ryotayama/Hayaemon/issues/76

**Comment by ryotayama** [comment]
作成しました₍₍ (ง*ᐛ)ว ⁾⁾
コピー機能とかは別途Issue立てます！
![dj4_tsbuwaevg8j](https://user-images.githubusercontent.com/6075785/43697401-0a732fb4-997f-11e8-90c2-3c10d44ac643.jpg)
