### ISSUE TITLE
FLACファイルを再生できるようにしてほしい

### ISSUE THREAD

**Issue by ryotayama** [ryotayama/Hayaemon_Android#92]
- Android版ver.1.58

https://twitter.com/Akeyroid7/status/1009813167952707585

FLACファイルを再生しようと再生ボタンを押したらフリーズしてしまったのですが、FLACは非対応でしょうか？

FLAC未対応です！
いずれ対応するかもしれません！

回答ありがとうございます。
(返信遅れてすみません)

確かに最近はAACでダウンロード販売が一般的ですし、僕みたいにスマホで聴くCDを無劣化で取り込んでる人も少ないですからね。

勿論FLAC対応して頂けると嬉しいのですが、せめてフリーズしないようにはして欲しいです(^^;

承知しました！！
ありがとうございます₍₍ (ง*ᐛ)ว ⁾⁾

https://twitter.com/ryota_yama/status/1029980931342254080

mkoi onnd（2018/08/10、11:08）
★★☆☆☆
このアプリはflacに対応していますか？端末に音楽ファイルが入っているのに、アプリ内に曲を追加しても再生出来ません

こちらから 2018/08/16 15:37 に返信
mkoi onndさん、はじめまして！
ハヤえもん開発者のりょーたと申します！
flacは未対応です。
いずれ対応する予定ですので、もうしばらくお待ちくださいね。
他にも何かありましたら、いつでもご連絡くださいませ。
ツイッター（@ryota_yama）からご連絡頂く事もできます！

**Comment by UmeboshiKantaro** [comment]
先ほど誤タップしてcloseしてしまいました(人ω<`;)ゴメンナサイ💦

https://twitter.com/ryota_yama/statuses/1031734541155618817
#ハヤえもんGooglePlayストアでのやりとり
Blue Smart（2018/07/30、11:45）
★★★★★
PC版を使っているのでこれからに期待のアプリです。 
SDカードの曲も聴けるようになってひとまず形になりましたね。後は.flac形式に対応したりフォルダ事にファイルを選べるようにしたりなど、いかにアプリが便利になっていくかに期待します！

https://twitter.com/ryota_yama/status/1039529241719713792?s=21
#ハヤえもんGooglePlayストアでのやりとり
虹スマッシュ（2018/09/10、14:15）
★★★★☆
イコライザーとか細かく設定できるのがすごくいい。 しかし、「flac」の拡張子のファイルが読み込めないのと、通知が表示されないのが残念……。

**Comment by ryotayama** [comment]
https://twitter.com/buccaneer4435/status/1086253631760789504
ハヤえもんがiOSでFLAC対応らしいのでAndroidに来たら課金します

いや、先に料金を払うのが筋なのでは？

ということでハヤえもん、広告解除した
